level_0 = {'terrain': '../../levels/0/level_0_Terrain.csv',
		'coins':'../../levels/0/level_0_Coin.csv',
		'fg palms':'../../levels/0/level_0_Fg_palms.csv',
		'bg palms':'../../levels/0/level_0_Bg_palms.csv',
		'crates': '../../levels/0/level_0_Crate.csv',
		'enemies':'../../levels/0/level_0_Enemies.csv',
		'constraints':'../../levels/0/level_0_Constraints.csv',
		'player': '../../levels/0/level_0_Player.csv',
		'grass': '../../levels/0/level_0_Grass.csv',
		'node_pos':(110,400),
		'unlock':1,
		'node_graphics': '../graphics/overworld/0'}
level_1 = {'terrain': '../../levels/1/level_1_Terrain.csv',
		'coins':'../../levels/1/level_1_Coin.csv',
		'fg palms':'../../levels/1/level_1_Fg_palms.csv',
		'bg palms':'../../levels/1/level_1_Bg_palms.csv',
		'crates': '../../levels/1/level_1_Crate.csv',
		'enemies':'../../levels/1/level_1_Enemies.csv',
		'constraints':'../../levels/1/level_1_Constraints.csv',
		'player': '../../levels/1/level_1_Player.csv',
		'grass': '../../levels/1/level_1_Grass.csv',
		'node_pos':(300,220), 'content': 'this is level 1', 'unlock':2, 'node_graphics': '../graphics/overworld/1'}
level_2 = {'terrain': '../../levels/2/level_2_Terrain.csv',
		'coins':'../../levels/2/level_2_Coin.csv',
		'fg palms':'../../levels/2/level_2_Fg_palms.csv',
		'bg palms':'../../levels/2/level_2_Bg_palms.csv',
		'crates': '../../levels/2/level_2_Crate.csv',
		'enemies':'../../levels/2/level_2_Enemies.csv',
		'constraints':'../../levels/2/level_2_Constraints.csv',
		'player': '../../levels/2/level_2_Player.csv',
		'grass': '../../levels/2/level_2_Grass.csv',
	'node_pos':(480,610), 'content': 'this is level 2', 'unlock':3, 'node_graphics': '../graphics/overworld/2'}
level_3 = {'terrain': '../../levels/3/level_3_Terrain.csv',
		'coins':'../../levels/3/level_3_Coin.csv',
		'fg palms':'../../levels/3/level_3_Fg_palms.csv',
		'bg palms':'../../levels/3/level_3_Bg_palms.csv',
		'crates': '../../levels/3/level_3_Crate.csv',
		'enemies':'../../levels/3/level_3_Enemies.csv',
		'constraints':'../../levels/3/level_3_Constraints.csv',
		'player': '../../levels/3/level_3_Player.csv',
		'grass': '../../levels/3/level_3_Grass.csv',
		'node_pos':(610,350), 'content': 'this is level 3', 'unlock':4, 'node_graphics': '../graphics/overworld/3'}
level_4 = {'terrain': '../../levels/4/level_4_Terrain.csv',
		'coins':'../../levels/4/level_4_Coin.csv',
		'fg palms':'../../levels/4/level_4_Fg_palms.csv',
		'bg palms':'../../levels/4/level_4_Bg_palms.csv',
		'crates': '../../levels/4/level_4_Crate.csv',
		'enemies':'../../levels/4/level_4_Enemies.csv',
		'constraints':'../../levels/4/level_4_Constraints.csv',
		'player': '../../levels/4/level_4_Player.csv',
		'grass': '../../levels/4/level_4_Grass.csv',
		'ship': '../../levels/4/level_4_Ship.csv',
		'sail': '../../levels/4/level_4_Sail.csv',
		'node_pos':(880,210), 'content': 'this is level 4', 'unlock':5, 'node_graphics': '../graphics/overworld/4'}
level_5 = {
		'terrain': '../../levels/5/level_5_Terrain.csv',
		'coins':'../../levels/5/level_5_Coin.csv',
		'platform':'../../levels/5/level_5_Platform.csv',
		'bg':'../../levels/5/level_5_Bg.csv',
		'crates': '../../levels/5/level_5_Crate.csv',
		'enemies':'../../levels/5/level_5_Enemies.csv',
		'constraints':'../../levels/5/level_5_Constraints.csv',
		'player': '../../levels/5/level_5_Player.csv',
		'chest': '../../levels/5/level_5_Chest.csv',
		'wall': '../../levels/5/level_5_Wall.csv',
		'node_pos':(1050,400), 'content': 'this is level 5', 'unlock':5, 'node_graphics': '../graphics/overworld/5'}

levels = {
	0: level_0,
	1: level_1,
	2: level_2,
	3: level_3,
	4: level_4,
	5: level_5}